# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Samuel Venters
title: Product Person
email: sam v {dot} yes (at) gmail {dot} com
website: sventers.github.io

# Social links
twitter_username: sam59490893
github_username:  sventers
# dribbble_username: 
# facebook_username: 
# flickr_username: 
instagram_username: samv_sammy
#linkedin_username: 
# pinterest_username: 
#youtube_username: 
# googleplus_username: +

# About Section
# about_title: About Me
about_profile_image: images/IMG_20180904_181534-01.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Sam. At the moment, I'm headed south in South America,
  slowly so as not to make it to Patagonia before summer (December 2019).
  On the way, I'm developing and testing a recommender system
  for finding accomodation for travellers based on social fit at the hostel.

  Tambien, estoy aprendiendo Espanol y algo surf
  

# Projects Section 
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  I'm interested in
  - visualizing change over time for {meaning of concepts, evolution of living things, history of science, etc} 
  - how to create perceptive frameworks and how they create categories from a totality of perception, 
  - and how to map high dimensional information into meaningful domains.

  Visited 40+ countries, lived in 3, fluent in 1.5 languages, and am forever learning

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
# - jekyll-seo-tag
