# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Sam V
title: 
email: did a (@) gmail .com
website: www.github.com/sventers/cv

# Social links
twitter_username: svent
github_username:  sventers
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: yy
# pinterest_username: jekyll
youtube_username: samv
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/doesntexist.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, this is attempt 1 to reformat and publish a decent resume, during and approaching after taking a two and a half year sabbatical to self educate and build while travelling the world.

  I am most skilled in: <mark>making plans</mark> and <mark>slow travel</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
