# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sam V
title: A bit of this and that
email: did a (@) gmail .com
website: www.github.com/sventers/cv

# Social links
twitter_username: sam59490893
github_username:  sventers
# dribbble_username: 
# facebook_username: 
# flickr_username: 
instagram_username: samv_sammy
#linkedin_username: 
# pinterest_username: 
#youtube_username: 
# googleplus_username: +

# About Section
# about_title: About Me
about_profile_image: images/IMG_20180904_181534-01.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Sam. At the moment, I'm somewhere in South America alternating travelling and working on two personal projects. I'm interested in how concepts change over time, how persons build unique perceptive frameworks of the world by categorization, and methods for resolving information gluttony.

  At the moment, I'm looking for a junior role in quantiative social research projects, and my top job criteria is good mentorship/leadership. Feel free to say hello over email.

  *Some of the information on this page is prospective*
# Projects Section 
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  I enjoy music, culture, sports, and life stories

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
# - jekyll-seo-tag
