# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Samuel Venters
title: Data Engineer
email: sam v {dot} yes (at) gmail {dot} com
website: sventers.github.io

# Social links
twitter_username: sam59490893
github_username:  sventers
# dribbble_username: 
# facebook_username: 
# flickr_username: 
instagram_username: samv_sammy
#linkedin_username: 
# pinterest_username: 
#youtube_username: 
# googleplus_username: +

# About Section
# about_title: About Me
about_profile_image: images/IMG_20180904_181534-01.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Sam. I have traveled full time since April 2017.
  In route, I constantly live the problem of search for
  lodging, food, and things to do. Finding the good things
  in life is half intention and half happenstance.
  I make maps to explore the edges of the backpacker's frontier spirit and 
  emotional response to new and old things in life.

  


  Personally also I am searching for a positon at a small to medium business 
  - that incorporates nlp
  - where the fundamental problem is search related
  - where there is someone able and willing to mentor
  
  Reach me at my email about anything

# Projects Section 
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: 

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
# - jekyll-seo-tag
